### ISSUE TITLE
CPU Utilization Question

### ISSUE THREAD

**Issue by tantrev** [slopp/Load-Test#1]
Just wondering if the 100% CPU utilization for the Open Source solution was for all CPUs on that node, or just the active thread (since the open source Shiny Server only allows 1 active process at a time)?

**Comment by slopp** [comment]
The 100% CPU utilization was for all cores on the node. Each node was supporting essentially 25 R processes (with a total count of 50 active processes, 1 open source shiny server per R process, plus the additional processes required to run Docker).

**Comment by tantrev** [comment]
Awesome, thanks for the clarification!
